export enum Theme {
    kahlaAuto,
    kahlaLight,
    kahlaDark,
    sakuraAuto,
    sakuraLight,
    sakuraDark,
    violetAuto,
    violetLight,
    violetDark,
    communistAuto,
    communistLight,
    communistDark,
    grassAuto,
    grassLight,
    grassDark,
}
